name: Convert SVG to Android Vector Drawable

on:
  push:
    paths:
      - 'icons/**'
  workflow_dispatch:

jobs:
  convert-svg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build JAR (if needed) - Check if JAR exists first
        run: |
          if [ ! -f "Svg2VectorAndroid-31.6.0.jar" ]; then
            echo "JAR file not found. Building..."
            chmod +x gradlew
            ./gradlew fatJar
          else
            echo "JAR file found. Skipping build."
          fi

      - name: Create output directory
        run: mkdir -p output

      - name: Convert SVG to XML
        run: java -jar Svg2VectorAndroid-31.6.0.jar -s icons -o output -e .xml

      - name: Upload converted icons
        uses: actions/upload-artifact@v3
        with:
          name: converted-icons
          path: output
