name: Build and Release JAR

on:
  push:
    tags:
      - 'v*'  
  workflow_dispatch:  

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    outputs:
      latest_tag: ${{ steps.get_tag.outputs.tag }}
      new_tag: ${{ steps.create_tag.outputs.new_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create new tag
  id: create_tag
  run: |
    # Extract the latest tag and increment the patch version (e.g., v1.0.0 -> v1.0.1)
    latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
    IFS='.' read -ra parts <<<"${latest_tag#v}"
    new_tag="v${parts[0]}.${parts[1]}.$((${parts[2]} + 1))"
    echo "New tag will be $new_tag"

    # Save new_tag to an environment file
    echo "new_tag=$new_tag" >> $GITHUB_ENV

    # Check if the tag already exists
    if git rev-parse "$new_tag" >/dev/null 2>&1; then
      echo "Tag $new_tag already exists. Exiting..."
      exit 1
    fi

    # Create and push the new tag
    git tag "$new_tag"
    git push origin "$new_tag"
  env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
