name: Build and Release JAR

on:
  push:
    tags:
      - 'v*'  # केवल 'v' से शुरू होने वाले टैग पर ट्रिगर होगा (उदा: v1.0)
  workflow_dispatch:  # मैन्युअल रूप से ट्रिगर करने के लिए

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Get the latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest tag is $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      - name: Create new tag
        id: create_tag
        run: |
          # Get the latest tag (e.g., v1.0.0 or v0.0.0 if no tags exist)
          tag="${{ steps.get_tag.outputs.tag }}"
          
          # Ensure the tag has the proper format (starting with 'v' and followed by numbers)
          if [[ ! "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Using v0.0.0 as default."
            tag="v0.0.0"
          fi

          # Extract the version parts (major, minor, patch)
          IFS='.' read -ra parts <<<"${tag#v}"  # 'v' को हटा कर केवल संस्करण नंबर पर ध्यान दें
          new_tag="v${parts[0]}.${parts[1]}.$((${parts[2]} + 1))"
          echo "New tag will be $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          
          # Check if the tag already exists on the remote and delete if it does
          if git rev-parse "refs/tags/$new_tag" >/dev/null 2>&1; then
            echo "Tag $new_tag already exists. Deleting it from the remote."
            git push --delete origin "$new_tag"  # Delete tag from remote
            git tag -d "$new_tag"  # Delete the local tag
          fi
          
          # Create and push the new tag
          git tag "$new_tag"
          git push origin "$new_tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build JAR file
        run: ./gradlew fatJar

      - name: Upload JAR to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'Svg2VectorAndroid-*.jar'  # यहाँ पर JAR फाइल का पैटर्न डालें
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.create_tag.outputs.new_tag }}  # Correctly pass the tag
          draft: false
          prerelease: false
          generateReleaseNotes: true # Optionally disable release notes generation
          makeLatest: true  # Mark this release as the latest one
          skipIfReleaseExists: false  # Do not skip if the release exists
