name: Build and Release JAR

on:
  push:
    tags:
      - 'v*'  # केवल 'v' से शुरू होने वाले टैग पर ट्रिगर होगा (उदा: v1.0)
  workflow_dispatch:  # मैन्युअल रूप से ट्रिगर करने के लिए

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Get the latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest tag is $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV

      - name: Create new tag
        id: create_tag
        run: |
          # Extract the latest tag and increment the patch version (e.g., v1.0.0 -> v1.0.1)
          IFS='.' read -ra parts <<<"${{ env.tag }}"
          new_tag="v${parts[0]}.${parts[1]}.$((${parts[2]} + 1))"
          echo "New tag will be $new_tag"
          git tag "$new_tag"
          git push origin "$new_tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build JAR file
        run: ./gradlew fatJar

      - name: Upload JAR to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'Svg2VectorAndroid-*.jar'  # यहाँ पर JAR फाइल का पैटर्न डालें
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ env.new_tag }}
          release_name: Release ${{ env.new_tag }}
          draft: false
          prerelease: false
