name: Build and Release JAR

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags starting with 'v' (e.g., v1.0)
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Get the latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest tag is $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      - name: Create new tag
        id: create_tag
        run: |
          tag="${{ steps.get_tag.outputs.tag }}"
          
          if [[ ! "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Using v0.0.0 as default."
            tag="v0.0.0"
          fi

          IFS='.' read -ra parts <<<"${tag#v}"
          new_tag="v${parts[0]}.${parts[1]}.$((${parts[2]} + 1))"
          echo "New tag will be $new_tag"
          echo "::set-output name=new_tag::$new_tag"
          
          if git ls-remote --tags origin | grep -q "refs/tags/$new_tag"; then
            echo "Tag $new_tag already exists. Deleting it from the remote."
            git push --delete origin "$new_tag"
            git tag -d "$new_tag"
          fi
          
          git tag "$new_tag"
          git push origin "$new_tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build JAR file
        run: ./gradlew fatJar

      - name: Upload JAR to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'Svg2VectorAndroid-*.jar'
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.create_tag.outputs.new_tag }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
          makeLatest: true
          skipIfReleaseExists: false
